version: '3'
services:
  data-display:
    container_name: data-display
    image: node:14
    command: node node_modules/nodemon/bin/nodemon.js --watch packages/data-display/src --inspect="0.0.0.0:9229" packages/data-display/src/index.js
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    environment:
      MYSQL_PORT: 3306
      MYSQL_PASS: 123qwe
      MYSQL_USER: root
      MYSQL_HOST: moondog-parser-db
    ports:
      - '3000:3000'
      - '9229:9229'
  ceneo-parser:
    container_name: ceneo-parser
    image: buildkite/puppeteer:latest
    command: node node_modules/nodemon/bin/nodemon.js --watch packages/ceneo-parser/src -x 'node packages/ceneo-parser/src/index.js || touch packages/ceneo-parser/src/index.js'
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    environment:
      MYSQL_PORT: 3306
      MYSQL_PASS: 123qwe
      MYSQL_USER: root
      MYSQL_HOST: moondog-parser-db
      CRON: '0 0 10 0 0 0 0'
    ports:
      - '9230:9229'
    depends_on:
      - moondog-parser-db
  hurtzoo-parser:
    container_name: hurtzoo-parser
    image: buildkite/puppeteer:latest
    command: node node_modules/nodemon/bin/nodemon.js --watch packages/hurtzoo-parser/src -x 'node packages/hurtzoo-parser/src/index.js || touch packages/hurtzoo-parser/src/index.js'
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    environment:
      MYSQL_PORT: 3306
      MYSQL_PASS: 123qwe
      MYSQL_USER: root
      MYSQL_HOST: moondog-parser-db
      SYNC_DB: 'false'
      CRON: '0 0 10 0 0 0 0'
    ports:
      - '9231:9229'
    depends_on:
      - moondog-parser-db
  moondog-parser-db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ~/projects/hurtzoo-parser/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
    ports:
      - '3308:3306'
