version: '3'
services:
  data-display:
    container_name: data-display
    image: node:14
    command: node packages/data-display/index.js
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    environment:
      MYSQL_PORT: 3306
      MYSQL_PASS: 123qwe
      MYSQL_USER: root
      MYSQL_HOST: moondog-parser-db
  ceneo-parser:
    container_name: ceneo-parser
    image: buildkite/puppeteer:latest
    command: node packages/ceneo-parser/src/index.js
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    environment:
      MYSQL_PORT: 3306
      MYSQL_PASS: 123qwe
      MYSQL_USER: root
      MYSQL_HOST: moondog-parser-db
  hurtzoo-parser:
    container_name: hurtzoo-parser
    image: buildkite/puppeteer:latest
    command: node packages/hurtzoo-parser/src/index.js
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    environment:
      MYSQL_PORT: 3306
      MYSQL_PASS: 123qwe
      MYSQL_USER: root
      MYSQL_HOST: moondog-parser-db
  moondog-parser-db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ~/projects/hurtzoo-parser/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
    ports:
      - '3307:3306'
