version: "3"
services:
  hurtzoo-parser:
    container_name: hurtzoo-parser
    image: buildkite/puppeteer:latest
    command: node packages/hurtzoo-parser/src/index.js
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    environment:
      MYSQL_PORT: 3306
      MYSQL_PASS: 123qwe
      MYSQL_USER: root
      MYSQL_HOST: moondog-parser-db
  moondog-parser-db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ~/projects/hurtzoo-parser/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
    ports:
    - "3307:3306"
